/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.Desktop;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Noite
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final long serialVersionUID = -3951331103458130053L;
    
    TelaPrincipal t;
    String usuario;
    String comando;
    String arquivo = null; 
    
    public TelaPrincipal() {
        initComponents();
        setIcon();
        this.setExtendedState(TelaPrincipal.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCliente = new javax.swing.JButton();
        jButtonProduto = new javax.swing.JButton();
        jButtonFornecedor = new javax.swing.JButton();
        jButtonVendas = new javax.swing.JButton();
        jButtonConsultaOrcamento = new javax.swing.JButton();
        jButtonFinanceiro = new javax.swing.JButton();
        jButtonMovimento = new javax.swing.JButton();
        jButtonPagamento = new javax.swing.JButton();
        jButtonOrcamento = new javax.swing.JButton();
        jButtonConsultaVenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonAjuda = new javax.swing.JButton();
        jButtonBackup = new javax.swing.JButton();
        jButtonRestaurarBackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Persom - Menu Principal");

        jButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/CLIENTE.png"))); // NOI18N
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jButtonProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PRODUT.png"))); // NOI18N
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });

        jButtonFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/FORNECEDOR.png"))); // NOI18N
        jButtonFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornecedorActionPerformed(evt);
            }
        });

        jButtonVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/VEND.png"))); // NOI18N
        jButtonVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendasActionPerformed(evt);
            }
        });

        jButtonConsultaOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/CONSULTAR ORCAMENTO.png"))); // NOI18N
        jButtonConsultaOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaOrcamentoActionPerformed(evt);
            }
        });

        jButtonFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/FINANCEIRO.png"))); // NOI18N
        jButtonFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinanceiroActionPerformed(evt);
            }
        });

        jButtonMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/MOVIMENTO.png"))); // NOI18N
        jButtonMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMovimentoActionPerformed(evt);
            }
        });

        jButtonPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PAGAMENT.png"))); // NOI18N
        jButtonPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagamentoActionPerformed(evt);
            }
        });

        jButtonOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ORCAMENTO.png"))); // NOI18N
        jButtonOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrcamentoActionPerformed(evt);
            }
        });

        jButtonConsultaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/CONSULTAR VENDAS.png"))); // NOI18N
        jButtonConsultaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaVendaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logoatu.png"))); // NOI18N

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ICONESAIR.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ICONEAJUDA.png"))); // NOI18N
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        jButtonBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/backup.png"))); // NOI18N
        jButtonBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackupActionPerformed(evt);
            }
        });

        jButtonRestaurarBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Restaura.png"))); // NOI18N
        jButtonRestaurarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaurarBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRestaurarBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConsultaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultaOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsultaOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonVendas))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonFinanceiro)
                        .addComponent(jButtonMovimento)
                        .addComponent(jButtonPagamento)
                        .addComponent(jButtonOrcamento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConsultaVenda)
                        .addGap(2, 2, 2)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRestaurarBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAjuda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendasActionPerformed
        new VendasGUI(this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVendasActionPerformed

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        new ClienteGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonConsultaOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaOrcamentoActionPerformed
         new ConsultaOrcamentoGUI().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonConsultaOrcamentoActionPerformed

    private void jButtonOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrcamentoActionPerformed
         new OrcamentoGUI(t).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonOrcamentoActionPerformed

    private void jButtonConsultaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaVendaActionPerformed
         new ConsultaVendasGUI().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonConsultaVendaActionPerformed

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
         new ProdutoGUI().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
    int x = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja sair ?","Usuário",JOptionPane.YES_NO_OPTION,2);
     if(x == 0){
     System.exit(0);   
      }else{
      }
    
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedorActionPerformed
         new FornecedoGUI().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonFornecedorActionPerformed

    private void jButtonMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMovimentoActionPerformed
         new MovimentoGUI().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonMovimentoActionPerformed

    private void jButtonPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagamentoActionPerformed
         new PagamentoGUI(t).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonPagamentoActionPerformed

    private void jButtonFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinanceiroActionPerformed
         new FinanceiroGUI().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonFinanceiroActionPerformed

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
    
        try {  
         Desktop desktop = Desktop.getDesktop();
         desktop.open(new File("C:\\Program Files\\Persom\\src\\Manual.pdf")); 
          
        } catch(Exception ex) {  
          ex.printStackTrace();  
          JOptionPane.showMessageDialog(null, "Erro no Desktop: " + ex);  
        }
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    private void jButtonBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackupActionPerformed
	        JFileChooser SalvarBackup = new JFileChooser();  
	        
               
	        SalvarBackup.setVisible(true);
	          
	        int result = SalvarBackup.showSaveDialog(this);  
	          
	        if (result == JFileChooser.APPROVE_OPTION) {  
	            arquivo = SalvarBackup.getSelectedFile().toString().concat(".sql");  
	  
	         File bck = new File(arquivo);  
	  
	         
                   if (!bck.isFile()) { 
                          
	                    comando = "C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin\\mysqldump.exe";  
	                    ProcessBuilder pb = new ProcessBuilder(comando, "--user=root", "--password=", "persom", "--result-file=" + arquivo);  
	                    try { 
                            pb.start();  
	                    JOptionPane.showMessageDialog(this,"Cópia de segurança realizada com sucesso","Backup",1);
                             
                             }catch (Exception e) {  
	                      JOptionPane.showMessageDialog(null,"Cópia de Segurança não pode ser realizada!!","Erro Backup",0); 
                             } 
	                } else { 
                           
	                   int x = JOptionPane.showConfirmDialog(null,"Um arquivo com esse nome já existe.\n Deseja substituí-lo ?","Backup já existe", JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE); 
                 
                                if(x == 0){  
	                        bck = new File(arquivo); 
	                        comando = "C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin\\mysqldump.exe"; 
	                        ProcessBuilder pb = new ProcessBuilder(comando, "--user=root", "--password=workjava15", "persom", "--result-file=" + bck );  
                                try {  
                                    pb.start();
                                    JOptionPane.showMessageDialog(this,"Cópia de segurança realizada com sucesso!","Backup",1);  
                                   
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null,"Cópia de Segurança não pode ser realizada!!","Erro Backup",2);
                                }
	                          }else{
                                    
                                }
                             }
                          }    
    }//GEN-LAST:event_jButtonBackupActionPerformed

    private void jButtonRestaurarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaurarBackupActionPerformed
        
        String x = JOptionPane.showInputDialog(null,"Informe a senha do administrador","Usuário",JOptionPane.QUESTION_MESSAGE);
        
        if(x.equals("")){
            restauraBackup();
         }else 
          JOptionPane.showMessageDialog(null,"Senha incorreta!!!","Usuário",0);
        
    }//GEN-LAST:event_jButtonRestaurarBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            
            
            
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonBackup;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonConsultaOrcamento;
    private javax.swing.JButton jButtonConsultaVenda;
    private javax.swing.JButton jButtonFinanceiro;
    private javax.swing.JButton jButtonFornecedor;
    private javax.swing.JButton jButtonMovimento;
    private javax.swing.JButton jButtonOrcamento;
    private javax.swing.JButton jButtonPagamento;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonRestaurarBackup;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVendas;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        this.setIconImage(new ImageIcon(getClass().getResource("/imagem/altofalante.png")).getImage());
    }
    
    public static void restauraBackup(){
         
          TelaPrincipal tela = new TelaPrincipal();
          String arq = "";
               
	  JFileChooser restaura = new JFileChooser();  
	  restaura.setDialogTitle("Selecione o arquivo de backup");
          int retorno = restaura.showOpenDialog(tela);
                  
         if(retorno == JFileChooser.APPROVE_OPTION){
           arq = restaura.getSelectedFile().getAbsolutePath();
          }
         
        String[] executeCmd = new String[]{"mysql","--user=root","--password=","persom","-e", "source " + arq};
        
        Process runtimeProcess;
        try {
 
            runtimeProcess = Runtime.getRuntime().exec(executeCmd);
            int processComplete = runtimeProcess.waitFor();
 
            if (processComplete == 0) {
                 JOptionPane.showMessageDialog(null,"Backup Restaurado com sucesso !","Restauração de Backup",1);
            } else {
                 JOptionPane.showMessageDialog(null,"Falha ao restaurar backup !","Erro ao Restaurar Backup",0);  
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
	         
  }